'use strict';
const $=id=>document.getElementById(id);
const state={csrf:'',status:null,devices:[],history:[],summary:[],trials:[],tab:'overview',busy:false,refreshing:false,profiles:[]};
const knownTabs=['overview','devices','online','history','settings'];
const errorText={ADMIN_PASSWORD_MISSING:'ADMIN_PASSWORD به برنامه نرسیده است. آن را در Envs ثبت و اپ را Restart کنید.',ADMIN_PASSWORD_TOO_SHORT:'رمز مدیر کمتر از ۱۶ کاراکتر است. ورود امن تا اصلاح آن غیرفعال می‌ماند.',AUTH_INITIALIZATION_FAILED:'آماده‌سازی ورود امن ناموفق است.',PUBLIC_DOMAIN_MISSING:'PUBLIC_DOMAIN به برنامه نرسیده است.',PUBLIC_DOMAIN_INVALID:'دامنه باید فقط hostname باشد؛ بدون http، مسیر یا قالب لینک.',STORAGE_UNAVAILABLE_OR_INVALID:'داده یا Volume قابل استفاده نیست. فایل قبلی خودکار حذف یا بازنویسی نشده است.',XRAY_NOT_FOUND:'باینری Xray پیدا نشد؛ ایمیج را بررسی کنید.',XRAY_VALIDATION_TIMEOUT:'بررسی تنظیمات هسته بیش از زمان مجاز طول کشید.',XRAY_CONFIG_REJECTED:'Xray تنظیمات را نپذیرفت.',CORE_IO_ERROR:'خطای دسترسی به فایل یا اجرای هسته.',XRAY_START_FAILED:'راه‌اندازی هسته ناموفق بود.',HISTORY_STORAGE_FAILED:'دیتابیس آمار آماده نیست؛ دستگاه‌های دارای سهمیه مجاز به اتصال نخواهند بود.',MONITOR_TRUST_CONFIG_INVALID:'تنظیم پراکسی مورد اعتماد نامعتبر است.',MONITOR_RELAY_UNAVAILABLE:'واسط پایش اجرا نشد. گزارش عیب‌یابی را بررسی کنید.'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=text;if(cls)n.className=cls;return n}
function notify(text,type='info'){$('message').className='message '+type;$('messageText').textContent=text}
function fmtNumber(n){return new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1}).format(n)}
function bytes(n){if(n===null||n===undefined)return 'نامشخص';n=Number(n);const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1000&&i<4){n/=1000;i++}return n.toFixed(i?1:0)+' '+u[i]}
function when(t){return t?new Intl.DateTimeFormat('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'short',timeStyle:'short'}).format(new Date(t*1000)):'هنوز ثبت نشده'}
function pill(text,color='neutral'){const p=el('span',null,'pill '+color);p.append(el('i',null,'dot '+color),el('span',text));return p}
function summaryFor(d){return state.summary.find(x=>x.device_id===d.id)||{active_connections:0,last_seen:null}}
function statusFor(d){if(!d.enabled||d.reason==='disabled')return ['غیرفعال','bad'];if(d.reason==='expired')return ['اعتبار تمام شده','warn'];if(d.reason==='exhausted')return ['سهمیه تمام شده','bad'];if(d.reason)return ['پایش در دسترس نیست','warn'];return summaryFor(d).active_connections>0?['متصل','good']:['بدون اتصال','neutral']}
function signedOut(){state.csrf='';state.devices=[];state.history=[];$('dashboard').classList.add('hidden');$('tabs').classList.add('hidden');$('logout').classList.add('hidden');$('login').classList.remove('hidden');closeModal(true)}
async function api(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),35000);try{const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const value=await r.json();if(!r.ok){if(r.status===401)signedOut();throw Error(value.error||'درخواست ناموفق بود')}return value}finally{clearTimeout(timer)}}
function renderSetup(codes,initializing){$('setup').replaceChildren();for(const code of codes)$('setup').append(el('p',errorText[code]||code));if(initializing)$('setup').append(el('p','پنل آماده است؛ بررسی اولیهٔ هسته در جریان است…'));$('setup').classList.toggle('hidden',!codes.length&&!initializing)}
async function boot(){try{const b=await api('bootstrap');$('password').disabled=!b.login_enabled;$('loginForm').querySelector('button').disabled=!b.login_enabled;renderSetup(b.errors,b.initializing);await refresh()}catch(e){notify('ارتباط با پنل برقرار نشد: '+e.message,'error')}}
function tab(name){state.tab=knownTabs.includes(name)?name:'overview';for(const t of knownTabs){$('view-'+t).classList.toggle('hidden',t!==state.tab);$('tab-'+t).setAttribute('aria-selected',String(t===state.tab));$('tab-'+t).tabIndex=t===state.tab?0:-1}if(location.hash!=='#'+state.tab)history.replaceState(null,'','#'+state.tab)}
async function refresh(){if(state.refreshing)return;state.refreshing=true;try{const s=await api('status');state.status=s;state.csrf=s.csrf;$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');$('tabs').classList.remove('hidden');$('logout').classList.remove('hidden');$('demo').classList.toggle('hidden',s.mode!=='demo');renderSetup(s.setup_errors||[],s.initializing);state.devices=(await api('devices')).devices;
try{const h=await api('history?device='+encodeURIComponent($('deviceFilter').value)+'&state='+encodeURIComponent($('stateFilter').value));state.history=h.connections;state.summary=h.summary;state.trials=h.trials}catch(e){state.history=[];state.summary=[];state.trials=[];notify(e.message,'error')}
if(!state.profiles.length)state.profiles=(await api('profiles')).items;
render();}catch(e){if(state.csrf)notify('دریافت وضعیت ناموفق: '+e.message,'error')}finally{state.refreshing=false}}
function render(){const s=state.status;const monitor=s.monitor||{};
$('headerHealth').replaceWith(Object.assign(pill(s.mode==='demo'?'حالت نمایشی':s.core_running?'هسته در حال اجرا':'هسته متوقف',s.core_running?'good':'warn'),{id:'headerHealth'}));
$('core').textContent=s.initializing?'در حال بررسی':s.mode==='demo'?'نمایشی':s.core_running?'در حال اجرا':'متوقف';$('core').style.color=s.core_running?'var(--green)':'var(--amber)';$('domain').textContent=s.domain;$('uptime').textContent=fmtNumber(Math.floor(s.uptime_seconds/60))+' دقیقه';$('memory').textContent='بیشینهٔ حافظهٔ پنل: '+s.panel_memory_mb+' MB';
const online=state.devices.filter(d=>summaryFor(d).active_connections>0).length;$('onlineMetric').textContent=fmtNumber(online);$('onlineCount').textContent=fmtNumber(online);$('deviceCount').textContent=fmtNumber(state.devices.length);$('connectionCount').textContent=fmtNumber(state.summary.reduce((n,d)=>n+d.active_connections,0))+' اتصال باز';$('totalUsage').textContent=state.devices.some(d=>d.used_bytes===null)?'نامشخص':bytes(state.devices.reduce((n,d)=>n+(d.used_bytes||0),0));
$('monitorBadge').replaceWith(Object.assign(pill(monitor.ready?'روشن':'خاموش / آماده نیست',monitor.ready?'good':'warn'),{id:'monitorBadge'}));$('monitorState').textContent=(monitor.error?(errorText[monitor.error]||monitor.error):monitor.enabled?'تاریخچهٔ خصوصی تا ۷ روز؛ شمارندهٔ سهمیه مستقل و ماندگار است.':'پایش خاموش یا حالت نمایشی است.')+(!monitor.trusted_proxy_configured?' IP واقعی: زنجیرهٔ پراکسی تأیید نشده.':'')+(!monitor.geo_available?' بانک کشور محلی نصب نیست.':'')+(monitor.persistence_error?' هشدار: خطای ثبت بخشی از آمار؛ دستگاه محدود در خطای شمارنده قطع می‌شود.':'');
$('logLevel').textContent=({warning:'هشدار',error:'فقط خطا',none:'خاموش'})[s.loglevel]||s.loglevel;
$('events').replaceChildren();for(const e of s.events.slice().reverse()){const row=el('div',null,'event');row.append(el('span',errorText[e.message]||e.message),el('time',when(Date.parse(e.time)/1000)));$('events').append(row)}
const selected=$('deviceFilter').value;$('deviceFilter').replaceChildren(new Option('همه',''));state.devices.forEach(d=>$('deviceFilter').add(new Option(d.name,d.id)));$('deviceFilter').value=selected;
renderDevices();renderHistory();renderProfiles()}
function actionButton(text,fn,cls='secondary'){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b}
function emptyRows(body,cols,title,detail){const tr=el('tr'),td=el('td',null,'empty');td.colSpan=cols;td.append(el('strong',title),el('span',detail));tr.append(td);body.append(tr)}
function cell(row,content){const n=el('td');if(content instanceof Node)n.append(content);else n.textContent=content;row.append(n);return n}
function renderDevices(){const q=$('deviceSearch').value.trim().toLocaleLowerCase();for(const [id,items] of [['deviceRows',state.devices.filter(d=>d.name.toLocaleLowerCase().includes(q))],['onlineRows',state.devices.filter(d=>summaryFor(d).active_connections>0)]]){const tbody=$(id);tbody.replaceChildren();for(const d of items){const tr=el('tr'),name=el('div',null,'device-idblock'),info=el('div');name.append(el('span','▣','device-avatar'),info);info.append(el('span',d.name,'device-name'),pill(...statusFor(d)));if(d.legacy)info.append(el('small','لینک قبلی حفظ شده','muted-small'));cell(tr,name);
const usage=el('div'),head=el('div',null,'meter-head'),used=d.used_bytes,limit=d.quota_bytes||0;const cap=el('span',limit?'از ':'نامحدود','muted');if(limit)cap.append(el('bdi',bytes(limit),'latin'));head.append(el('b',bytes(used),'latin'),cap);const progress=el('div',null,'meter '+(!limit?'unlimited':used>=limit?'bad':used/limit>=.8?'warn':''));const fill=el('span');fill.style.width=limit&&used!==null?Math.min(100,used/limit*100)+'%':'0%';progress.append(fill);if(limit&&used!==null){progress.setAttribute('role','progressbar');progress.setAttribute('aria-label','مصرف '+d.name);progress.setAttribute('aria-valuemin','0');progress.setAttribute('aria-valuemax','100');progress.setAttribute('aria-valuenow',String(Math.min(100,Math.floor(used/limit*100))))}const remaining=el('small',limit?'باقی‌مانده: ':'ارسال + دریافت · سقف تعیین نشده','muted-small');if(limit)remaining.append(el('bdi',bytes(d.remaining_bytes),'latin'));usage.append(head,progress,remaining);if(d.basis==='retained-history')usage.append(el('small','مبنای اولیه: تاریخچهٔ باقی‌مانده','muted-small'));cell(tr,usage);
const time=el('div');time.append(el('span',d.duration_days?fmtNumber(d.duration_days)+' روز از اولین اتصال':'بدون انقضا'),el('small',d.expires_at?'پایان: '+when(d.expires_at):d.duration_days?'هنوز شروع نشده':'اولین مشاهده: '+when(d.first_seen),'muted-small'));cell(tr,time);
const stats=summaryFor(d),activity=el('div');activity.append(el('b',fmtNumber(stats.active_connections)+' اتصال'),el('small',when(stats.last_seen),'muted-small'));cell(tr,activity);const acts=el('div',null,'row-actions');acts.append(actionButton('لینک',()=>linkModal(d),'link-button'),actionButton('⋯',()=>moreModal(d),'more-button'));acts.lastChild.setAttribute('aria-label','عملیات '+d.name);cell(tr,acts);tbody.append(tr)}if(!items.length)emptyRows(tbody,5,id==='onlineRows'?'فعلاً دستگاه متصلی مشاهده نمی‌شود.':'دستگاهی پیدا نشد.',id==='onlineRows'?'این بخش بر اساس اتصال باز است، نه صرفاً فعال‌بودن اعتبار.':'از «افزودن دستگاه» استفاده کنید یا جست‌وجو را تغییر دهید.')}}
function renderHistory(){$('historyRows').replaceChildren();for(const c of state.history){const tr=el('tr');cell(tr,state.devices.find(d=>d.id===c.device_id)?.name||'دستگاه سابق');const ip=el('div');ip.append(el('span',c.client_ip||'IP نامشخص','latin'),el('small',(c.country||'کشور نامشخص')+(!c.client_ip?' · واسط: '+(c.peer_ip||'—'):''),'muted-small'));cell(tr,ip);cell(tr,when(c.started));cell(tr,when(c.ended||c.last_seen));cell(tr,fmtNumber(c.duration_seconds)+' ثانیه');const traffic=el('span',bytes(c.up)+' / '+bytes(c.down),'latin');cell(tr,traffic);cell(tr,pill(...({active:['باز','good'],closed:['بسته','neutral'],interrupted:['پایان نامشخص','warn']})[c.state]));$('historyRows').append(tr)}if(!state.history.length)emptyRows($('historyRows'),7,'هنوز اتصال قابل‌نمایشی ثبت نشده است.','اتصال جدید یا فیلتر دیگری را بررسی کنید؛ دادهٔ ساختگی تولید نمی‌شود.')}
function renderProfiles(){$('profiles').replaceChildren();for(const p of state.profiles){const card=el('div',null,'profile');card.append(el('h3',p.name),pill(({available:'مسیر فعلی',manual:'تنظیم دستی', 'not-deployed':'فعال نشده'})[p.state],p.state==='available'?'good':'neutral'),el('p',p.description));$('profiles').append(card)}$('trialRows').replaceChildren();state.trials.forEach(t=>{const row=el('div',null,'event');row.append(el('span',[t.network,t.client,({working:'کار کرد',failed:'ناموفق',unstable:'ناپایدار'})[t.result],t.latency_ms===null?'':t.latency_ms+' ms'].join(' · ')),el('time',when(t.created)));$('trialRows').append(row)})}
// All confirmations and edits use a single accessible in-app dialog.
let modalHandler=null,lastFocus=null,modalBusy=false;
function closeModal(force=false){if(modalBusy&&!force)return;if($('modal').open){if(typeof $('modal').close==='function')$('modal').close();else $('modal').removeAttribute('open')}$('modalBody').replaceChildren();modalHandler=null;if(lastFocus?.isConnected)lastFocus.focus()}
function openModal(title,description,content,onSubmit,label='ذخیرهٔ تغییرات',danger=false){if(state.busy)return;closeModal();lastFocus=document.activeElement;$('modalTitle').textContent=title;$('modalDescription').textContent=description;$('modalBody').replaceChildren(content);$('modalError').classList.add('hidden');$('modalSubmit').textContent=label;$('modalSubmit').className=danger?'danger-button':'primary';$('modalSubmit').classList.toggle('hidden',!onSubmit);$('modalCancel').textContent=onSubmit?'انصراف':'بستن';modalHandler=onSubmit;if(typeof $('modal').showModal==='function')$('modal').showModal();else $('modal').setAttribute('open','');setTimeout(()=>$('modalBody').querySelector('input,select,textarea,button')?.focus(),0)}
function field(id,label,type='text',value='',hint=''){const wrap=el('div',null,'field'),lab=el('label',label);lab.htmlFor=id;const input=el('input');input.id=id;input.type=type;input.value=value;wrap.append(lab,input);if(hint)wrap.append(el('small',hint,'hint'));return {wrap,input}}
function selectField(id,label,options,value){const wrap=el('div',null,'field'),lab=el('label',label);lab.htmlFor=id;const input=el('select');input.id=id;options.forEach(([v,t])=>input.add(new Option(t,v)));input.value=value;wrap.append(lab,input);return {wrap,input}}
function checkField(id,label,checked=false){const wrap=el('div',null,'check-row'),input=el('input');input.type='checkbox';input.id=id;input.checked=checked;const lab=el('label',label);lab.htmlFor=id;wrap.append(input,lab);return {wrap,input}}
async function mutate(path,value){notify('در حال اعمال تغییرات…','busy');await api(path,value);await refresh();notify('عملیات با موفقیت انجام شد.','success')}
function confirmModal(title,description,callback,danger=false,label='تأیید و ادامه'){openModal(title,description,el('div'),callback,label,danger)}
function editModal(d=null){const content=el('div'),name=field('editName','نام دستگاه / کاربر','text',d?.name||'');name.input.required=true;name.input.maxLength=80;content.append(name.wrap);const grid=el('div',null,'form-grid'),quota=field('editQuota','سقف مصرف (GB)','number',d?(d.quota_bytes||0)/1e9:5,'هر GB برابر ۱٬۰۰۰٬۰۰۰٬۰۰۰ بایت است. صفر = نامحدود.'),days=field('editDays','اعتبار از اولین اتصال (روز)','number',d?.duration_days??10,'روز تقویمی؛ نه مجموع ساعت‌های آنلاین. صفر = بدون انقضا.');quota.input.min=0;quota.input.max=1000000;quota.input.step='any';quota.input.required=true;days.input.min=0;days.input.max=36500;days.input.step='1';days.input.required=true;grid.append(quota.wrap,days.wrap);content.append(grid);if(d)content.append(el('p','مصرف شمارش‌شده: '+bytes(d.used_bytes)+' · اولین مشاهده: '+when(d.first_seen)+'. ویرایش، مصرف یا شروع اعتبار را صفر نمی‌کند.','modal-info'));content.append(el('p','در اتمام سهمیه یا اعتبار، اتصال‌های این دستگاه قطع می‌شوند. ذخیرهٔ این تغییر در نسخهٔ فعلی هسته را بازراه‌اندازی می‌کند.','notice'));openModal(d?'ویرایش دستگاه':'افزودن دستگاه',d?'لینک فعلی حفظ می‌شود؛ سقف کمتر از مصرف فعلی می‌تواند دستگاه را فوراً مسدود کند.':'برای هر دستگاه یک نام و لینک مستقل بسازید.',content,async()=>{const bytesValue=Math.round(Number(quota.input.value)*1e9);if(!Number.isSafeInteger(bytesValue))throw Error('حجم نامعتبر است');const data={name:name.input.value,quota_bytes:bytesValue,duration_days:Number(days.input.value)};if(d)Object.assign(data,{id:d.id,operation:'edit'});await mutate(d?'device':'devices',data)},d?'ذخیرهٔ تغییرات':'ساخت دستگاه')}
function moreModal(d){const content=el('div',null,'modal-menu');content.append(actionButton('ویرایش نام، سهمیه و اعتبار',()=>{closeModal();editModal(d)}),actionButton(d.enabled?'غیرفعال‌کردن دستگاه':'فعال‌کردن دستگاه',()=>{closeModal();confirmModal(d.enabled?'غیرفعال‌کردن دستگاه':'فعال‌کردن دستگاه','تغییر وضعیت هسته را بازراه‌اندازی می‌کند. فعال‌کردن، سهمیه یا تاریخ انقضا را تمدید نمی‌کند.',()=>mutate('device',{id:d.id,operation:d.enabled?'disable':'enable'}),d.enabled)}),actionButton('تعویض کلید اتصال',()=>{closeModal();confirmModal('تعویض کلید اتصال','لینک قبلی این دستگاه باطل می‌شود؛ مصرف و اعتبار زمانی حفظ می‌شوند. اتصال‌های جاری بازراه‌اندازی می‌شوند.',()=>mutate('device',{id:d.id,operation:'rotate'}),true)},'danger-button'));openModal('مدیریت دستگاه',d.name,content,null)}
async function linkModal(d){if(!d)return;try{const link=(await api('link?device='+encodeURIComponent(d.id))).link;const content=el('div'),area=el('textarea');area.className='link-area';area.id='link';area.readOnly=true;area.value=link;area.setAttribute('aria-label','لینک خصوصی اتصال');content.append(area,actionButton('کپی لینک',async()=>{try{await navigator.clipboard.writeText(link);notify('لینک کپی شد. آن را خصوصی نگه دارید.','success')}catch{area.focus();area.select();notify('کپی خودکار در دسترس نیست؛ متن انتخاب‌شده را کپی کنید.')}}));openModal('لینک اختصاصی',d.name+' · این لینک محرمانه است و فقط روی دستگاه موردنظر وارد شود.',content,null)}catch(e){notify(e.message,'error')}}
function saveFile(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function serverModal(){const f=selectField('editLevel','سطح ثبت خطای هسته',[['warning','هشدار · پیش‌فرض'],['error','فقط خطا'],['none','خاموش']],state.status.loglevel);openModal('تنظیمات هستهٔ سرور','اعمال تنظیمات، اتصال‌های جاری را لحظه‌ای قطع می‌کند. خروجی خام دارای اطلاعات ترافیک ذخیره نمی‌شود.',f.wrap,()=>mutate('settings',{loglevel:f.input.value}),'اعمال و راه‌اندازی مجدد')}
function rangeValue(value,min,max){if(!/^\d+(?:-\d+)?$/.test(value))throw Error('بازه باید مانند 100-200 باشد');const [a,b=a]=value.split('-').map(Number);if(a<min||b>max||a>b)throw Error('بازه خارج از محدوده است');return value}
function buildClientConfig(link,options){const uri=new URL(link);if(uri.protocol!=='vless:')throw Error('لینک نامعتبر');const port=Number(options.port);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('پورت محلی نامعتبر');const concurrency=Number(options.concurrency)||8;if(!Number.isInteger(concurrency)||concurrency<1||concurrency>32)throw Error('تعداد جریان Mux نامعتبر');const stream={network:'ws',security:'tls',tlsSettings:{serverName:uri.searchParams.get('sni'),fingerprint:'chrome',allowInsecure:false},wsSettings:{path:uri.searchParams.get('path')||'/connect',headers:{Host:uri.searchParams.get('host')}}};const proxy={tag:'proxy',protocol:'vless',settings:{vnext:[{address:uri.hostname,port:Number(uri.port)||443,users:[{id:decodeURIComponent(uri.username),encryption:'none'}]}]},streamSettings:stream,mux:{enabled:Boolean(options.mux),concurrency}};const outbounds=[proxy];if(options.fragment){stream.sockopt={dialerProxy:'fragment'};outbounds.push({tag:'fragment',protocol:'freedom',settings:{domainStrategy:options.ipv4?'UseIPv4':'AsIs',fragment:{packets:'tlshello',length:rangeValue(options.length,1,65535),interval:rangeValue(options.interval,0,1000)}}})}else if(options.ipv4){stream.sockopt={domainStrategy:'UseIPv4'}}return {log:{loglevel:'warning'},inbounds:[{listen:'127.0.0.1',port,protocol:'socks',settings:{auth:'noauth',udp:true}}],outbounds}}
window.buildClientConfig=buildClientConfig;
function clientModal(){const enabled=state.devices.filter(d=>d.enabled&&!d.reason);if(!enabled.length){notify('ابتدا یک دستگاه مجاز برای دریافت پروفایل لازم است.','error');return}const content=el('div'),device=selectField('profileDevice','دستگاه',enabled.map(d=>[d.id,d.name]),enabled[0].id),fragment=checkField('profileFragment','Fragment آزمایشی · فقط tlshello',false),mux=checkField('profileMux','Mux · چندجریانی، پیش‌فرض خاموش',false),ipv4=checkField('profileIPv4','ترجیح IPv4 برای اتصال به سرور',false),port=field('profilePort','پورت SOCKS محلی','number',10818,'این خروجی مستقل است؛ پورت نباید با برنامهٔ دیگری تداخل داشته باشد.'),concurrency=field('profileConcurrency','تعداد جریان Mux','number',8),length=field('profileLength','طول Fragment (بایت)','text','100-200'),interval=field('profileInterval','فاصلهٔ Fragment (میلی‌ثانیه)','text','10-20');port.input.min=1024;port.input.max=65535;concurrency.input.min=1;concurrency.input.max=32;const grid=el('div',null,'form-grid');grid.append(length.wrap,interval.wrap,port.wrap,concurrency.wrap);content.append(device.wrap,fragment.wrap,mux.wrap,ipv4.wrap,grid,el('p','بازه‌های Fragment نمونهٔ مستندات Xray هستند، نه مقدار تضمین‌شده برای همراه اول. TLS با بررسی گواهی روشن می‌ماند. DNS سیستم تغییر نمی‌کند.','modal-info'));const sync=()=>{length.input.disabled=interval.input.disabled=!fragment.input.checked;concurrency.input.disabled=!mux.input.checked};fragment.input.onchange=mux.input.onchange=sync;sync();openModal('تنظیم پروفایل کلاینت','خروجی خصوصی Xray-core JSON؛ روی سرور و کلاینت فعال شما اعمال نمی‌شود. سازگاری Custom Config با نسخهٔ کلاینت را جدا بررسی کنید.',content,async()=>{const link=(await api('link?device='+encodeURIComponent(device.input.value))).link;const result=buildClientConfig(link,{port:port.input.value,mux:mux.input.checked,concurrency:concurrency.input.value,fragment:fragment.input.checked,length:length.input.value,interval:interval.input.value,ipv4:ipv4.input.checked});saveFile('darvazeh-private-xray-client.json',result);notify('فایل خصوصی کلاینت آماده شد؛ تنظیمات سرور تغییر نکرد.','success');return false},'دانلود پروفایل خصوصی')}
function trialModal(){const content=el('div'),network=field('trialNetwork','شبکه / اپراتور'),client=field('trialClient','کلاینت و نسخه'),profile=selectField('trialProfile','پروفایل',[['ws-baseline','WS فعلی'],['ws-client-tuning','تنظیمات کلاینت'],['xhttp-research','XHTTP در محیط مستقل']], 'ws-baseline'),result=selectField('trialResult','نتیجه',[['working','کار کرد'],['unstable','ناپایدار'],['failed','وصل نشد']],'working'),latency=field('trialLatency','تأخیر اختیاری (ms)','number');network.input.required=client.input.required=true;network.input.maxLength=client.input.maxLength=80;latency.input.min=0;latency.input.max=600000;const grid=el('div',null,'form-grid');grid.append(network.wrap,client.wrap,profile.wrap,result.wrap,latency.wrap);content.append(grid);openModal('ثبت آزمایش اتصال','نتیجهٔ خودتان را ثبت کنید. این ورودی، گزارش دستی است و تنظیمات سرور را تغییر نمی‌دهد.',content,()=>mutate('trial',{network:network.input.value,client:client.input.value,profile:profile.input.value,result:result.input.value,latency_ms:latency.input.value===''?null:Number(latency.input.value)}),'ثبت نتیجه')}
$('modalForm').onsubmit=async e=>{e.preventDefault();if(modalBusy||!modalHandler)return;modalBusy=state.busy=true;$('modalSubmit').disabled=true;$('modalCancel').disabled=true;$('modalClose').disabled=true;$('modalError').classList.add('hidden');try{const keep=await modalHandler();if(keep!==false)closeModal(true)}catch(err){$('modalError').textContent=err.message;$('modalError').classList.remove('hidden');notify(err.message,'error')}finally{modalBusy=state.busy=false;$('modalSubmit').disabled=false;$('modalCancel').disabled=false;$('modalClose').disabled=false}};
$('modalClose').onclick=$('modalCancel').onclick=()=>closeModal();$('modal').addEventListener('cancel',e=>{e.preventDefault();closeModal()});$('modal').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeModal()}if(e.key==='Tab'){const focusable=Array.from($('modal').querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')).filter(n=>!n.classList.contains('hidden'));const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await api('login',{password:$('password').value});$('password').value='';await refresh();notify('خوش آمدید؛ پنل به‌روز است.','success')}catch(err){notify(err.message,'error')}};
$('logout').onclick=()=>confirmModal('خروج از پنل','نشست مدیریت بسته می‌شود؛ اتصال VPN دستگاه‌ها تغییری نمی‌کند.',async()=>{await api('logout',{});signedOut();notify('از پنل خارج شدید.')},false,'خروج');
$('dismissMessage').onclick=()=>$('message').classList.add('hidden');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('tabs').addEventListener('keydown',e=>{const i=knownTabs.indexOf(state.tab);let n;if(e.key==='ArrowLeft')n=(i+1)%knownTabs.length;if(e.key==='ArrowRight')n=(i+knownTabs.length-1)%knownTabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=knownTabs.length-1;if(n!==undefined){e.preventDefault();tab(knownTabs[n]);$('tab-'+knownTabs[n]).focus()}});
document.querySelectorAll('.add-device').forEach(b=>b.onclick=()=>editModal());document.querySelectorAll('.refresh').forEach(b=>b.onclick=async()=>{await refresh();notify('اطلاعات به‌روز شد.')});$('deviceSearch').oninput=renderDevices;$('historyRefresh').onclick=refresh;$('deviceFilter').onchange=$('stateFilter').onchange=refresh;
$('legacyLink').onclick=()=>linkModal(state.devices.find(d=>d.id==='legacy'));$('serverSettings').onclick=serverModal;$('restart').onclick=()=>confirmModal('راه‌اندازی مجدد هسته','همهٔ اتصال‌های جاری لحظه‌ای قطع می‌شوند؛ سهمیه و اعتبار دستگاه‌ها حفظ می‌شوند.',()=>mutate('restart',{}),false,'راه‌اندازی مجدد');$('clientSettings').onclick=clientModal;$('newTrial').onclick=trialModal;
$('purgeHistory').onclick=()=>confirmModal('پاک‌سازی تاریخچه','سوابق اتصال‌های بسته و آزمایش‌ها حذف می‌شوند. مصرف سهمیه، اعتبار، لینک و دستگاه‌ها پاک یا صفر نمی‌شوند. این حذف برگشت‌پذیر نیست.',()=>mutate('history/purge',{confirm:'DELETE_HISTORY'}),true,'پاک‌سازی سوابق');$('historyExport').onclick=()=>confirmModal('دانلود تاریخچهٔ خصوصی','این فایل شامل IP و زمان اتصال است. فقط ۲۰۰ ردیف همین فیلتر صادر می‌شود؛ آن را عمومی منتشر نکنید.',async()=>{saveFile('darvazeh-private-history.json',{warning:'Private connection metadata',connections:state.history});notify('خروجی خصوصی آماده شد.','success')},false,'دانلود خصوصی');$('report').onclick=async()=>{try{saveFile('darvazeh-report.json',await api('report'));notify('گزارش بدون کلید و IP کاربران آماده شد. دامنهٔ سرور در آن وجود دارد.','success')}catch(e){notify(e.message,'error')}};
window.addEventListener('hashchange',()=>tab(location.hash.slice(1)));tab(location.hash.slice(1));boot();setInterval(()=>{if(!state.busy){if(state.csrf)refresh();else boot()}},10000);
